Medable/ResearchStack

backbone/build.gradle

Match the build tools and libraries with cortex and axon

update build tools

---

backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentVisualStepLayout.java

first we need to display the content url, if there is no content url we need to display content html,.. if both are missing, we display normal content

fix priorities on learn more section

---

backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
backbone/src/main/res/values-es/strings.xml
backbone/src/main/res/values/strings.xml

* Add strings texts on Spanish
* Add date formatters on Spanish
* Change some hardcoded texts for resource strings

Multiple Language Support Spanish

---

backbone/build.gradle

update build tools version from 26.0.3 to 27.0.3
change compile to implementation in build gradle file

Update gradle to delete warnings

---

backbone/build.gradle

* Update the gradle files to target API 26, remove Retrolambda, and update java compatibility to 1.8 (from 1.7)
* Smoke test, ensure things compile.

RES-7: Remove retrolambda; upgrade to Java 1.8, target api 26.

---

backbone/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

* In yesterday's PR, these two files were not updated and they should.
* See #34 for reference.

Update Gradle version (to match the other projects)

---

backbone/src/main/assets/consent.css
backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
backbone/src/main/java/org/researchstack/backbone/utils/RSHTMLPDFWriter.java

images in consent files were broken when exporting to pdf files. The changes to fix this issue are:
1- Set webview base url to axon assets folder.
2- Reformat consent html code, so that the signature image does not use an entire page.

PAT-619: Signed Content: Two broken images are displayed

---

backbone/src/main/java/org/researchstack/backbone/task/OrderedTask.java
backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
backbone/src/main/java/org/researchstack/backbone/ui/step/body/DecimalQuestionBody.java
backbone/src/main/java/org/researchstack/backbone/ui/step/body/IntegerQuestionBody.java
backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentVisualStepLayout.java
backbone/src/main/java/org/researchstack/backbone/ui/views/PinCodeLayout.java
backbone/src/main/java/org/researchstack/backbone/utils/LocaleUtils.java

Fix a couple of strings that were not translated properly. Fixes 
https://jira.devops.medable.com/browse/PAT-984
https://jira.devops.medable.com/browse/PAT-985
https://jira.devops.medable.com/browse/PAT-986
https://jira.devops.medable.com/browse/PAT-987
To test, you will need to checkout https://gitlab.medable.com/axon/android/sdk/merge_requests/414/
* Env: int-dev
* Org: hybridstudy
* Study: Multi language
Set phone as German
Launch Study
Choose Spanish
Join study (Do not login)
Go through consent form
Check that the next button is in spanish
When a popup dialog is shown, check that the language is in spanish.

PAT-984 Missing translations

---

backbone/build.gradle

VERSION BUMP: Update version from 1.4.0 to 1.5.0.

---

backbone/src/main/java/org/researchstack/backbone/step/ConsentVisualStep.java
backbone/src/main/java/org/researchstack/backbone/task/Task.java
backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentVisualStepLayout.java
backbone/src/main/java/org/researchstack/backbone/ui/step/layout/InstructionStepLayout.java
backbone/src/main/res/values-bg-rBG/strings.xml
backbone/src/main/res/values-de-rDE/strings.xml
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-hu-rHU/strings.xml
backbone/src/main/res/values-pl-rPL/strings.xml

This MR updates all the classes related with making the consent use the localized version of strings.

PAT-1013: Update RS consent's related classes to use localized data.

---

backbone/src/main/java/org/researchstack/backbone/utils/LocaleUtils.java
backbone/src/test/java/org/researchstack/backbone/task/TaskTest.java

This MR fix broken tests and add missing null validations

PAT-1013: Fix broken tests.

---

backbone/src/main/java/org/researchstack/backbone/ui/step/body/BodyAnswer.java
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-hu-rHU/strings.xml

The MR add usage to LocaleUtils.getLocalizedString in BodyAnswer. It also adds missing Hungarian translations

PAT-1013: Add missing strings & add missing Locale.getLocalized call

---

backbone/src/test/java/org/researchstack/backbone/task/TaskTest.java

PAT-1013: Fix broken test.

---

backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentVisualStepLayout.java
backbone/src/main/java/org/researchstack/backbone/ui/step/layout/InstructionStepLayout.java

PAT-1046 Missing translations

---

backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentSignatureStepLayout.java

PAT-990 Change date format

---

backbone/src/main/java/org/researchstack/backbone/step/Step.java
backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java

Implement the hidden step on the Step model and use it on ViewTaskActivity.
If the step is hidden, just save the default value (if provide) and go to the next step (if there is).
Same with the back, if the previous step is hidden, go back another time.
Close [PAT-1125](https://jira.devops.medable.com/browse/PAT-1125)

[PAT-1125] Add feature hidden step

---

backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rMX/strings.xml
backbone/src/main/res/values-es-rUS/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml
backbone/src/main/res/values-sv-rSE/strings.xml
backbone/src/main/res/values-tr-rTR/strings.xml
backbone/src/main/res/values-uk-rUA/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml

Objective: The Goal of this MR is to add a list of new languages for our 4.8.1 release
Added Languages: en-GB, en-NZ, es-MX, es-US, fr-BE, fr-CA, fr-CN, fr-FR, it-IT, nl-BE (update), nl-NL, ru-UA, sv-SE, tr-TR, uk-UA, zh-CN, zh-TW, cs-CZ, da-DK, de-CH, en-AU

PAT-1149 : Add new locales

---

backbone/src/main/res/values-fr-rCA/strings.xml

This MR is a support for the newly added locale to allow the pipeline build to pass on Gitlab.

PAT-1149: Fix apostrophe error to allow pipeline build

---

backbone/src/main/res/layout/rsb_activity_step_switcher.xml
backbone/src/main/res/layout/rsb_activity_video_viewer.xml
backbone/src/main/res/layout/rsb_activity_web_document.xml
backbone/src/main/res/layout/rsb_item_chart_pie.xml
backbone/src/main/res/layout/rsb_item_checkbox.xml
backbone/src/main/res/layout/rsb_item_date_view.xml
backbone/src/main/res/layout/rsb_item_edit_duration.xml
backbone/src/main/res/layout/rsb_item_edit_text.xml
backbone/src/main/res/layout/rsb_item_edit_text_compact.xml
backbone/src/main/res/layout/rsb_item_radio.xml
backbone/src/main/res/layout/rsb_item_text_view_title_compact.xml
backbone/src/main/res/layout/rsb_layout_fixed_submit_bar.xml
backbone/src/main/res/layout/rsb_layout_toolbar.xml
backbone/src/main/res/layout/rsb_progress.xml
backbone/src/main/res/layout/rsb_step_layout.xml
backbone/src/main/res/layout/rsb_step_layout_consent_doc.xml
backbone/src/main/res/layout/rsb_step_layout_consent_signature.xml
backbone/src/main/res/layout/rsb_step_layout_consent_visual.xml
backbone/src/main/res/layout/rsb_step_layout_form_body.xml
backbone/src/main/res/layout/rsb_step_layout_instruction.xml
backbone/src/main/res/layout/rsb_step_layout_pincode.xml
backbone/src/main/res/layout/rsb_view_chart_bar.xml
backbone/src/main/res/layout/rsb_view_chart_line.xml
backbone/src/main/res/layout/rsb_view_chart_pie.xml
backbone/src/main/res/layout/rsb_view_chart_progress.xml
backbone/src/main/res/layout/rsb_view_empty.xml
backbone/src/main/res/layout/rsb_view_icon_tab.xml
backbone/src/main/res/layout/rsb_view_submitbar.xml

Although there are no visible changes/fixes included in this PR that could easily be tested, what you could do just to make sure that everything is still working as before, is trying to run any random task/steps, and make sure the response is uploaded properly

PAT-916: Prevent Tapjacking Attacks.

---

backbone/build.gradle

Update RS version to 1.4.1 for 4.8.1 version.

PAT-1169: Update version name to 1.4.1 for 4.8.1

---

backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java

- Fixes alignment of the signature, name, and date. and makes sure they're all printed in the same PDF page.
- To test this use the following credentials
- Environment: Int-dev
- Multi-Language study
- No need to login, just join the study, then take the consent task
- After finishing consent task click View to show PDF.
- Try with different languages (fr_be, fr_ca, fr_ch, de_ch, es_us, es_mx)
- The Signature, Name, and Date at the bottom should all be aligned with each other and inside the same PDF page and aligned with each other. (the issue stated that some of the name, signature, and date fields were in page 1, and others in page 2)
- https://jira.devops.medable.com/browse/PAT-1186
Solves PAT-1186

PAT-1186: PDF Document - Align signature, name and date.

---

backbone/src/main/res/values-bg-rBG/strings.xml
backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-de-rDE/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rMX/strings.xml
backbone/src/main/res/values-es-rUS/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-pl-rPL/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml
backbone/src/main/res/values-sv-rSE/strings.xml
backbone/src/main/res/values-tr-rTR/strings.xml
backbone/src/main/res/values-uk-rUA/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml

The Goal of this MR is to add a list of new languages and updates some locales Strings file for our 4.8.1 release

PAT-1262: Update Locales

---

backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml

Update es_ES and it_IT locales

PAT-1262: Add new locales

---

backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rUS/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml

This MR update strings according to the findings identified in PAT-1298.
Closes PAT-1298

PAT-1298: update missing updates

---

CHANGELOG.md

Update CHANGELOG.md for 4.8.1 release.

Update CHANGELOG.md for 4.8.1 release.

---

backbone/build.gradle

PAT-1311 Update Project MIN SDK TO API 23

---

backbone/build.gradle
backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
backbone/src/main/java/org/researchstack/backbone/ui/PinCodeActivity.java
backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
backbone/src/main/java/org/researchstack/backbone/ui/ViewVideoActivity.java
backbone/src/main/java/org/researchstack/backbone/ui/ViewWebDocumentActivity.java

This PR introduces a new variable (USE_SECURE_FLAG) to make sure that when the app/module is compiled with this variable set to TRUE only, then FLAG_SECURE flags.
1) You can clone PAT project and all its submodules: git clone --recurse-submodules https://gitlab.medable.com/axon/android/app.git PatientApp-1368
2) Move to task/PAT-1368-Automation_add_secure_flag branch in PAT, AXON y RS modules
3) Compile the app using with a device connected to your environment:
3.1) ./gradlew installAutomatedFlaskRelease. By doing this, you will be able to capture screenshots.
3.2) ./gradlew installFlaskRelease. By doing this, you will NOT be able to capture screenshots.
Closes: PAT-1368

PAT-1368: automation add secure flag

---

backbone/src/main/res/drawable/rsb_reviewstep_skipped_rect.xml
backbone/src/main/res/layout/rsb_email_step_layout.xml
backbone/src/main/res/values/colors.xml

- Added Email step to ReviewStep list
- https://jira.devops.medable.com/browse/PAT-1340
**To test this**
- env: Int-dev
- Join study and take the task "Email ReviewStep"
Closes PAT-1340

PAT-1340 add email ReviewStep

---

backbone/src/main/res/layout/rsb_barcode_scanner_review_step_layout.xml

PAT-1336: Add barcode scanner step layout file

Create Barcode Scanner Step Layout file

---

backbone/src/main/res/layout/rsb_numeric_step_layout.xml

- Added Numeric step UI to ReviewStep
- https://jira.devops.medable.com/browse/PAT-1347
**To test this:**
- Env: Int-dev
- Join Study and take the "ReviewStep Numeric" task

PAT-1347: Add Numeric Step UI for ReviewStep

---

backbone/src/main/res/layout/rsb_text_scale_step_layout.xml

- This creates a layout file for the Text Scale Step.
- https://jira.devops.medable.com/browse/PAT-1350

PAT-1350: Create Layout for text scale step

---

backbone/src/main/res/layout/rsb_text_step_layout.xml

- Added text step UI to ReviewStep
- https://jira.devops.medable.com/browse/PAT-1348
**To test this:**
- Env: Int-dev
- Join Study and take the "ReviewStep Text" task

PAT-1348: Add text step UI for ReviewStep

---

backbone/src/main/res/layout/rsb_text_choice_step_layout.xml

To test this:
- Env: Int-dev
- Join Study
- Take the "ReviewStep Text Choice" task
- https://jira.devops.medable.com/browse/PAT-1349
Closes PAT-1349

PAT-1349: add text choice review step

---

backbone/src/main/res/layout/rsb_value_picker_step_layout.xml

* Creates a layout file for the Value Picker Step
[link to ticket](https://jira.devops.medable.com/secure/RapidBoard.jspa?rapidView=130&view=detail&selectedIssue=PAT-1353)

PAT-1353: Create layout for value picker step

---

backbone/src/main/res/layout/rsb_web_view_step_layout.xml

* Creates a layout file for the Web View Step
[Link to ticket](https://jira.devops.medable.com/browse/PAT-1354)

PAT-1354: Create webView step layout file

---

backbone/src/main/res/layout/rsb_integer_scale_step_layout.xml

- This creates a layout file for the Integer Scale Step.
- https://jira.devops.medable.com/browse/PAT-1345

    This creates a layout file for the Integer Scale Step.

---

backbone/src/main/res/layout/rsb_integer_scale_step_layout.xml

Removed Answer max field length

Removed Answer max field length

---

backbone/src/main/res/layout/rsb_review_step_edit_button_layout.xml

* Remove a deprecated attribute I introduced.

Fix deprecated constraint layout attribute.

---

backbone/src/main/res/layout/rsb_autocomplete_step_layout.xml
backbone/src/main/res/layout/rsb_barcode_scanner_review_step_layout.xml
backbone/src/main/res/layout/rsb_boolean_step_layout.xml
backbone/src/main/res/layout/rsb_continuous_scale_step_layout.xml
backbone/src/main/res/layout/rsb_date_time_step_layout.xml
backbone/src/main/res/layout/rsb_email_step_layout.xml
backbone/src/main/res/layout/rsb_form_step_layout.xml
backbone/src/main/res/layout/rsb_image_capture_step_layout.xml
backbone/src/main/res/layout/rsb_image_choice_step_layout.xml
backbone/src/main/res/layout/rsb_instruction_step_layout.xml
backbone/src/main/res/layout/rsb_integer_scale_step_layout.xml
backbone/src/main/res/layout/rsb_location_step_layout.xml
backbone/src/main/res/layout/rsb_numeric_step_layout.xml
backbone/src/main/res/layout/rsb_review_step_edit_button_layout.xml
backbone/src/main/res/layout/rsb_text_choice_step_layout.xml
backbone/src/main/res/layout/rsb_text_scale_step_layout.xml
backbone/src/main/res/layout/rsb_text_step_layout.xml
backbone/src/main/res/layout/rsb_time_intervals_step_layout.xml
backbone/src/main/res/layout/rsb_time_of_day_step_layout.xml
backbone/src/main/res/layout/rsb_value_picker_step_layout.xml
backbone/src/main/res/layout/rsb_web_view_step_layout.xml

- Environment: Int-dev
**Steps:**
- Open Patient App
- Use the credentials above
- Join Study
- Take the task "ReviewStep ALL" and reach to the Review step
- https://jira.devops.medable.com/browse/PAT-1389

PAT-1389: Fix edit buttons overlap with answers

---

backbone/build.gradle

Version bump from 1.5.0 to 1.6.0

Version bump from 1.5.0 to 1.6.0

---

backbone/src/main/res/values-ja-rJP/strings.xml
backbone/src/main/res/values-ru-rRU/strings.xml

- Add Japanese and Russian to rc/flask-4.9.0.
- Removed all (translatable="false") strings from Japanese and Russian files.

PAT-1420: Add Japanese and Russian to rc/flask-4.9.0

---

backbone/src/main/res/values-bg-rBG/strings.xml
backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-de-rDE/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-es-rMX/strings.xml
backbone/src/main/res/values-es-rUS/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-hu-rHU/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-ja-rJP/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-pl-rPL/strings.xml
backbone/src/main/res/values-ru-rRU/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml
backbone/src/main/res/values-sv-rSE/strings.xml
backbone/src/main/res/values-tr-rTR/strings.xml
backbone/src/main/res/values-uk-rUA/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml
backbone/src/main/res/values/strings.xml

This small PR is about removing an unused string KEY from the project in all languages.
Relates to PAT-1425

PAT-1425: Remove unused key

---

backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt

- Fixed Location step to show maps in all task steps.
- In this PR I've just added a function to `TaskActivity` that returns the current step fragment, and I'm using that in Axon's `RSLocationBody`
-https://jira.devops.medable.com/browse/PAT-1403
Fixes PAT-1403

PAT-1403 fix overlap step views

---

backbone/build.gradle

* Merge the latest development version in our topic branch, in preparation for integration.

Integrate development into review step

---

backbone/build.gradle

Adding new dev & prod build flavors.

PAT-1393: Allow DEV and PROD builds to be kicked off from CI.

---

backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt

Fix the issue when you click on the cancel button then discard then touch the back button on the top the title change and the back button do nothing
Answers the steps in the task until you reach Review step, clicks on the pencil,  you will see the sep you want to edit, click on cancel on bottom bar, then dismiss it, then click back in the action bar

PAT-1453 : Fix back button when user dismiss cancel dialog

---

backbone/src/main/res/values-bg-rBG/strings.xml
backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-de-rDE/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-es-rMX/strings.xml
backbone/src/main/res/values-es-rUS/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-hu-rHU/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-pl-rPL/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml
backbone/src/main/res/values-sv-rSE/strings.xml
backbone/src/main/res/values-tr-rTR/strings.xml
backbone/src/main/res/values-uk-rUA/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml
backbone/src/main/res/values/strings.xml

Update/Add new Strings associated with Save Alert and Edit Alert

PAT-1443 : Add/Update dialogs alerts text

---

backbone/src/main/java/org/researchstack/backbone/result/TaskResult.java
backbone/src/test/java/org/researchstack/backbone/result/TaskResultTest.java

* Provide a Unit Test for the operations TaskResult has to conduct and that make ReviewStep possible.
* PAT-1477

PAT-1477: Add TaskResult unit test

---

backbone/src/main/java/org/researchstack/backbone/step/Step.java
backbone/src/test/java/org/researchstack/backbone/step/StepTest.java

* Provide a simple unit test for the old ResearchStack `Step` class.
* The Step class has a few peculiar decisions hiding in the code, the unit test is designed to document and test those behaviors in case they are changed in the future. 
* Run StepTest.java.

PAT-1497: Step Unit Test

---

CHANGELOG.md

Update CHANGELOG.md for 4.9.0 release.

Update CHANGELOG.md for 4.9.0 release.

---

backbone/src/main/res/layout/rsb_web_view_step_layout.xml

- Fixed PAT-1531: Adding the edit button for WebView in ReviewStep
- Environment: Int-Dev
**Steps:**
2. Join Study
3. Take task `ReviewStep WebView`
4. Reach to ReviewStep
5. Edit first step
**Expected:**
1. The Edit button should appear
2. The user should be able to edit the first task, and the result should change according to the user selection
- Axon: bug/PAT-1531_Add_edit_to_WebView
- RS: bug/PAT-1531_Add_edit_to_WebView
- https://jira.devops.medable.com/browse/PAT-1531
Closes PAT-1531

PAT-1531: Added Edit button for WebView step in ReviewStep

---

backbone/build.gradle

Updating Research stack versioning for PAT 4.9.1 RC

PAT-1559: Update ResearchStack version to 1.5.1

---

backbone/build.gradle
build.gradle

* Update libraries to the latest stable versions in RS. 
* `./gradlew clean test assembleDebug`

PAT:1571: January 2020 lib updates

---

backbone/build.gradle

* Fix the build.
`./gradlew clean assembleDebug`

Add missing variable in gradle to avoid coupling the modules.

---

backbone/src/main/res/values-ko-rKR/strings.xml

PAT-1566: Import PAT translated strings for Korean (ko_KR)

---

backbone/build.gradle

allow useSecureFlalg to be overwriten from the root project

PAT-1578: dev flavor should not use SECURE_FLAG by default

---

CHANGELOG.md

Update CHANGELOG.md for 4.9.1 release.

---

CHANGELOG.md
backbone/build.gradle
backbone/src/main/res/values-ko-rKR/strings.xml

merging 4.9.1 into master-medable

Task/merge 4.9.1 into master

---

backbone/build.gradle

Update build.gradle name to 1.7.0 (part of 4.11) release.

VERSION BUMP: Version bump to 1.7.0/4.11.

---

backbone/src/main/java/org/researchstack/backbone/ui/views/SubmitBar.java

- Fixed PAT-1750: Steps next button shows as "skip"
-  Environment: QA
-  Org: hybridstudy
-  Study: Multilanguage
-  Test account: daniel.nadaya+telev1@medable.com/qpal1010
**Steps**
1.  Launch patient app
2.  Set the study of the preconditions
3.  Log in with the user
4.  Go to Continuous scale task
**Actual Result:** The 'Next' button is showing as 'Skip'
**Expected Result:** The 'Next' button is shows correctly.
- PAT: rc/flask-4.10.0
- Axon: rc/flask-4.10.0
- RS: bug/PAT-1750_Next_button_shows_Skip
- Cortex: rc/flask-4.10.0
- https://jira.devops.medable.com/browse/PAT-1750
Closes PAT-1750

PAT-1750: next button shows skip

---

CHANGELOG.md

4.10.0: Update CHANGELOG for 1.6.0.

---

backbone/src/main/res/values-bg-rBG/strings.xml
backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-de-rDE/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-es-rMX/strings.xml
backbone/src/main/res/values-es-rUS/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-hu-rHU/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-ja-rJP/strings.xml
backbone/src/main/res/values-ko-rKR/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-pl-rPL/strings.xml
backbone/src/main/res/values-ru-rRU/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml
backbone/src/main/res/values-sv-rSE/strings.xml
backbone/src/main/res/values-tr-rTR/strings.xml
backbone/src/main/res/values-uk-rUA/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml
backbone/src/main/res/values/strings.xml

This MR consists in removing old strings that are no longer in used for RS or any other project.
The following entries were removed: 
```<string name="rsb_consent_learn_more">Learn More</string> 
<string name="rsb_consent_share_title">Sharing Options</string> 
<string name="rsb_consent_share_widely">Share my data with %1$s and qualified researchers 
worldwide
</string>
<string name="rsb_consent_share_no">Not sharing your data</string> 
<string name="rsb_consent_share_description"><![CDATA[%1$s will receive your study data from your
participation in this study. \n\nSharing your coded study data more broadly (without
information such as your name) may benefit this and future research.<br/><br/><a href="%2$s">
Learn more about data sharing</a>]]>
</string> 
<string …
```

PATAND-20: Remove unused strings from Research Stack project.

---

backbone/build.gradle

This MR is about updating version to 1.8

Version bump to 1.8

---

backbone/build.gradle
gradle/wrapper/gradle-wrapper.properties

The objectif of these MRs are to update all libs inside the project
- PAT: task/PATAND-165_update_lib
- Axon: task/PATAND-165_update_lib
- RS: task/PATAND-165_update_lib
- Cortex: task/PATAND-165_update_lib
There is not really a specific scenario. Just use the application and normally everything need to work as usual.
Close [PATAND-165](https://jira.devops.medable.com/browse/PATAND-165)

PATAND-165: Update libs

---

backbone/build.gradle

This MR is about updating version name to 1.7.2

PATAND-214: Update version name to 1.7.2/4.11.2

---

backbone/src/main/res/values-bg-rBG/strings.xml
backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-de-rDE/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-es-rMX/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-hu-rHU/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-ja-rJP/strings.xml
backbone/src/main/res/values-ko-rKR/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-pl-rPL/strings.xml
backbone/src/main/res/values-ru-rRU/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml
backbone/src/main/res/values-sv-rSE/strings.xml
backbone/src/main/res/values-tr-rTR/strings.xml
backbone/src/main/res/values-uk-rUA/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml

PAT: task/PATAND-194
Axon: task/PATAND-194
Cortex: development
RS: task/PATAND-194
Org: hybridstudy
Study: ML
1. launch the app
2. Join study/ login
3. Change languages 
4. Please test all the tasks and observe time window strings are being localized.

PATAND-194: Import localized strings

---

backbone/src/main/res/values-bg-rBG/strings.xml
backbone/src/main/res/values-cs-rCZ/strings.xml
backbone/src/main/res/values-da-rDK/strings.xml
backbone/src/main/res/values-de-rCH/strings.xml
backbone/src/main/res/values-de-rDE/strings.xml
backbone/src/main/res/values-en-rAU/strings.xml
backbone/src/main/res/values-en-rGB/strings.xml
backbone/src/main/res/values-en-rNZ/strings.xml
backbone/src/main/res/values-es-rES/strings.xml
backbone/src/main/res/values-es-rMX/strings.xml
backbone/src/main/res/values-es-rUS/strings.xml
backbone/src/main/res/values-fr-rBE/strings.xml
backbone/src/main/res/values-fr-rCA/strings.xml
backbone/src/main/res/values-fr-rCH/strings.xml
backbone/src/main/res/values-fr-rFR/strings.xml
backbone/src/main/res/values-hu-rHU/strings.xml
backbone/src/main/res/values-it-rIT/strings.xml
backbone/src/main/res/values-ja-rJP/strings.xml
backbone/src/main/res/values-ko-rKR/strings.xml
backbone/src/main/res/values-nl-rBE/strings.xml
backbone/src/main/res/values-nl-rNL/strings.xml
backbone/src/main/res/values-pl-rPL/strings.xml
backbone/src/main/res/values-ru-rRU/strings.xml
backbone/src/main/res/values-ru-rUA/strings.xml
backbone/src/main/res/values-sv-rSE/strings.xml
backbone/src/main/res/values-tr-rTR/strings.xml
backbone/src/main/res/values-uk-rUA/strings.xml
backbone/src/main/res/values-zh-rCN/strings.xml
backbone/src/main/res/values-zh-rTW/strings.xml
backbone/src/main/res/values/strings.xml

Add tools:ignore="ResourceName" tools:override="true" too all the material strings for all the languages.

PATAND-279: Add tools:override to material strings.

---

CHANGELOG.md

Updating CHANGELOG to force new build

PATAND-279 Update Changelog

---

backbone/build.gradle

VERSION BUMP: Update version to 4.12.0.

---

backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
backbone/src/main/res/layout/rsb_step_layout.xml
backbone/src/main/res/values/dimens.xml

Implement the change for the common part : the survey layout
- RS: task/PATAND-237_update_survey_layout
- Study: QA-Regression
- User: matias.battaglia+4@medable.com/qpal1010
- Task: T03 - Boolean
* Login if it's not the case
* Start the right task
Expected: 
* The header (title and description with the divider) will fit the [zeplin](https://app.zeplin.io/project/5dc576e8f5b84283ac09b02a/screen/5dcaf47f059b3f01311053c3)
Part of PATAND-237

PATAND-237 : Update the common survey layout

---

backbone/src/main/res/values/dimens.xml
backbone/src/main/res/values/styles.xml

Add just some style and dimension missing for PATAND-238

PATAND-238: Add missing style and dim

---

backbone/src/main/java/org/researchstack/backbone/ui/step/body/FormBody.java
backbone/src/main/res/layout/rsb_form_step_divider.xml
backbone/src/main/res/values/dimens.xml

* Task PATAND-243: Form step
* The Form step is just adding the other steps view in a linear layout vertical view .. the only thing added here is a divider between each step 
* Environment: Int-Dev
* Org: hybridstudy
* Study: Multi language study
* [mohamed_andela+enro1@medable.com](mailto:mohamed_andela+enro1@medable.com) / qpal1010
**Steps:**
1. Join Study
1. Open Form step
**Expected:**
1. The step UI is similar to the following Zeplin links
https://zpl.io/aMjxxRN
https://zpl.io/VxQqqwk
https://zpl.io/aBdAAW0
https://zpl.io/V49nnGM
https://zpl.io/aMjxxXr
https://zpl.io/VOpEEyl
https://zpl.io/VxQjrlk
https://zpl.io/am7xxee
* PAT: task/PATAND-243
* Axon: task/PATAND-243
* RS: task/PATAND-243
* Cortex: development
* …

PATAND-243: Form step

---

backbone/src/main/java/org/researchstack/backbone/ui/task/ReviewStepFullScreenImageActivity.kt
backbone/src/main/res/layout/rsb_activity_full_screen_image.xml

Fix the localization of the edit button
- RS: task/PATAND-271_edit_not_localized
- Study: ML
- angela+ml@medable.com/qpal1010
* Log in
* Change the language of PAT 
* Start the task : Image capture task
* Do all the step to access the review step
* Open any image on full screen (right-top of any image)
Expected: 
* The button on the right-bottom will be localized
Close PATAND-271

PATAND-271: Fixing the text and add marging to the button

---

backbone/src/main/res/values-b+es+419/strings.xml
backbone/src/main/res/values-ms-rMY/strings.xml
backbone/src/main/res/values-pt-rBR/strings.xml
backbone/src/main/res/values-sk-rSK/strings.xml
backbone/src/main/res/values-ta-rIN/strings.xml

This MR is about introducing 5 new locales: 
ms_MY, ta_IN, pt_BR, es_419 (see the special folder pattern) and sk_SK

PATAND-292: Import new locales.

---

backbone/build.gradle

Version bump to 1.9.0 in develop-master

Version bump to 1.9
