Medable/ResearchStack

- backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
https://gitlab.medable.com/axon/android/sdk/issues/141
Removed back arrow for first steps.
Also fix screen transitions on branched tasks (back and forward)
> fix bug 141 back arrow

- backbone/src/main/java/org/researchstack/backbone/step/Step.java
- backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
This allows a reference to the ActionBar so our custom steps can access it.
> Provide a reference to ActionBar from Axon steps

- backbone/src/main/java/org/researchstack/backbone/step/Step.java
This prevents ActionBar from being serialized in our steps when the app is backgrounded.
https://jira.devops.medable.com/browse/PAT-281
> Transient so it isn't serialized onPause()

- backbone/src/main/java/org/researchstack/backbone/ui/views/FixedSubmitBarLayout.java
Sometimes, the "Next" button is not displayed in a boolean step. This is so, because the "submitBar"  view which contains the next button is moved to a wrong Y position, so the button completely disappears
JIRA ticket is https://jira.devops.medable.com/browse/PAT-407
I'm not sure about why `guidePosition` and `yLimit` were needed here, but they are the reason of this issue (causing next button to be hidden)
I'm not removing them completely from the code, until we make sure everything works as expected
> PAT-407: Boolean Step: The next button of the boolean steps is not displayed when it has a custom string property and the previous step is a text step

- backbone/src/main/java/org/researchstack/backbone/ui/step/body/BodyAnswer.java
Make BodyAnswer accept strings for reason instead of only resource ids.
This will allow to show messages that came from the server and not only the ones from resources.
> bug/PAT-534 Make BodyAnswer accept strings for reason instead of only resource ids

- backbone/build.gradle
- build.gradle
* Minor tech_debt that we can get out of the way to pave the road for a future migration to Androidx and latest libraries; it's now impossible to migrate to `androidx` support libraries due to the multiple old-dependencies we still carry; this is a _very small_ step forwards. We can compile with API 28, as long as we're targeting API 27 (can't upgrade to 28 yet).
* Update the support libraries (27.1.0 to 27.1.1).
* Do not use the root project ext variables for critical versioning, since this prevents the individual project from being individually assembled (outside of PAT) which kind of defeats the purpose of having separate projects to begin with. ;)
> Minor Toolchain Upgrade

- backbone/build.gradle
- build.gradle
Fix C.I. issues with API 28. Downgrade to API 27 for both compile and target.
> Compile ResearchStack with API 27.

- backbone/src/main/java/org/researchstack/backbone/ui/views/FixedSubmitBarLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/views/ObservableScrollView.java
* Provide a better ScrollView (`NestedScrollView`) instead of the old `ScrollView`.
* The nested version has a better handling of other nested components (like RecyclerViews) which Backbone uses to present Single/Multiple choice FormSteps.
* Each FormStep is a list of QuestionStep, which in turn, when needed, instantiate `RSTextChoice[Single|Multiple]Body` instances, depending. These instances contain a TextView label for the title of the question, and a RecyclerView to present each Combo or Radio button, depending whether it's single or multiple.
* All this is wrapped in a custom `ObservableScrollView` which supports adding a listener to proxy the scroll action callback; this is old, and no longer needed when on API 23, but since we're still targeting API 19, I left it there.
* Cleanup …
> PAT-611: Fix form question options UI

- backbone/src/main/java/org/researchstack/backbone/ui/step/body/FormBody.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
* Ensure that a formBody with *all* optional steps, allows you to tap NEXT without any validation interfering.
* We need a small Axon Change in backbone, sadly so this needs to be integrated before it can be tested.
* If you still want to give it a try, be my guest:
```
Environment: Test
Study: Test Hybrid Study
Task: [FROZEN FOR PAT-824] do not modify
account: franco+2@medable.com qpal1010 
PIN 950181
```
**You must change one line of code in Backbone or this will not work**
In `RSNumericBody.java`, find the line:
```
float entryValue = 0;
```
And replace it with:
```
float entryValue = step.isOptional() && hasMinimum ? step.getMinimumFloat() : 0;
```
This is around line 114 in the `public BodyAnswer getBodyAnswerState() {` method.
The above change is coming in a PR in …
> PAT-824: SurveyLayout/FormBody: check if fields are optional when validating.

- backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/PinCodeActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
- backbone/src/main/java/org/researchstack/backbone/utils/LocaleUtils.java
This brings multilanguage to tasks.
Preferred locale has been saved in shared preferences by Axon. We are retrieving it and set the new Locale in `attachBaseContext`.
To test, please checkout `https://gitlab.medable.com/axon/android/sdk/merge_requests/413` in Axon SDK and `https://gitlab.medable.com/axon/android/app/merge_requests/530` in Patient App
Env: int-dev
Organization: hybridstudy
Study: Multilanguage
* Set your phone to German
* Launch study
* Select Spanish as preferred language
* Login into app (angela+ml4@medable.com / qpal1010)
* Open the boolean task 
* Verify that the task is in spanish
> RES-8 Implement Multilanguage in tasks

- backbone/src/main/java/org/researchstack/backbone/utils/LocaleUtils.java
This MR updates LocaleUtils so args are processed when getLocalizedString is invoked.
> PAT-1013: Make sure getString is called with extra args by default.

- backbone/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
* Migrate from Appcompat/Support v27.1.1 to v28.0.0 and Target API 28.
* It's best to observe commit by commit (not the merge ones) to better grasp the important changes.
> PAT-1094: Migrate to Support Library 28 | Target API 28

- backbone/src/main/res/values-fr-rFR/strings.xml
- backbone/src/main/res/values-nl-rBE/strings.xml
Issue: When the user reaches the signature consent step of a consent task, the app crashes when the preferred locale is set to either French (France/fr_FR) or Dutch (Belgium/nl_BE).
Context information
- Org: Hybridstudy
- Study: Multi-language
How to test:
1- Checkout PAT `rc-4.8.1` branch and go to the context study
2- Select Join Study and set the Locale to either France (Belgium) or Dutch (Belgium) (Test both)
3- Complete the consent task and observe that the App crashes when you complete the signature step
4- Checkout `bug/PAT-1173_fix_consent_signature_app_crash`
5- Clear the App Data
6- Run the App and go over step 2 and 3 and with the same context study
7- The app shouldn't crash for neither fr_FR and nl_BE after the signature step
> PAT-1173: Fix Signature Consent App crash when Preferred Locale is changed

- backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/permissions/PermissionListener.java
- backbone/src/main/java/org/researchstack/backbone/ui/permissions/PermissionMediator.java
- backbone/src/main/java/org/researchstack/backbone/ui/permissions/PermissionResult.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
* Request permissions in an Android M+ compatible way across all three types of steps. 
* Android API "shouldRequestRationale" returns false if you have never requested the permission. The only way to know this, is by keeping track of it, hence why I get the SharedPreferences and store the permission name with a "true" if I requested it (regardless of whether the user accepted it or not).
* After that, it's just a matter of following the flag + the result of the request. 
* File reformatting across the modified files, sorry for the noise.
0. **Start with a fresh install (that is, uninstall your current flask version).** 
1. Start and log in to QA/Hybridstudy/Fede Study (fforciniti+qa1@medable.com | qpal1010)
2. **do not grant** permissions during the welcome screens, reach the end and …
> [PAT-731]: Unify Location, Barcode, and Img Capture permission behavior.

- backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
- backbone/src/main/java/org/researchstack/backbone/utils/RSHTMLPDFWriter.java
- Fixes alignment of the signature, name, and date. and makes sure they're all printed in the same PDF page.
- To test this use the following credentials
- Environment: Int-dev
- Multi-Language study
- No need to login, just join the study, then take the consent task
- After finishing consent task click View to show PDF.
- The Signature, Name, and Date at the bottom should all be aligned with each other and inside the same PDF page.
- https://jira.devops.medable.com/browse/PAT-1186
Solves PAT-1186
> PAT-1186: Fixed PDF consent form to align signature, name, and date in the same page

- backbone/build.gradle
* Keep the dependencies up 2 date.
- AppCompat 1.0.2 -> 1.1.0
- Gson 2.4 -> 2.8.5
- Lifecycle 2.0.0 -> 2.1.0
1. Checkout `task/PAT-1229_october2019_dependencies_update ` **in both CORTEX and RS**.
2. Smoke test, nothing fancy as you can see in the changes.
> PAT-1229: Update Dependencies, CompileSDK, and BuildTool versions.

- backbone/src/main/java/org/researchstack/backbone/ui/step/body/DateQuestionBody.java
Fix the issue with the hour and minute not retrain when a new date is selected.
You can use the following study to perform the test:
environment: int-dev
organization: jaimesdesousagomes
study: Test study
public user is enough. No need to log in
task : AllDateTimeType
You can use the first step to select a date and a time. Normally if you do next and back the same date is already selected and when changing this one the date hour and minute need to be the same as selected.
> PAT-1119 : Set the hour and minute for the timePicker to the last version selected

- backbone/src/main/java/org/researchstack/backbone/ui/PinCodeActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/ViewVideoActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/ViewWebDocumentActivity.java
The purpose of this ticket is making screenshot blocking works properly in HUAWEI devices. The current implementation does not work in that brand.
This refactoring will just set the flag on onCreate() and we will no longer need to unset it.
> PAT-1236: Update screenshot blocking  for Huawei devices

- backbone/src/main/java/org/researchstack/backbone/ui/ConsentViewTaskActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
- consent task was not working, there was a NPE when trying to complete a consent task
- Also fixed navigation issue when pressing device "recent apps" button. When pressing this button, and then selecting the App from the recent's Apps list, the activity moved immediately to the next step
how to test this:
Fix 1:
- Try to complete a consent task (you should complete it successfully, without any crash)
Fix 2
- Open a task with more than 1 step
- With the task opened, press "recent Apps" button
- Select Flask from the recent apps
- When selecting Flask from the recent apps, selected step should be the same, the app should not navigate to the next step
NOTE: 
1- on PAT, checkout bug/review-step-consent-task-fix
2- axon, checkout task/PAT-1294-review-step
3- RS, checkout …
> Fixed not working consent task & step navigation when pressing "recent tasks" button.

- backbone/src/main/res/values-bg-rBG/strings.xml
- backbone/src/main/res/values-cs-rCZ/strings.xml
- backbone/src/main/res/values-da-rDK/strings.xml
- backbone/src/main/res/values-de-rCH/strings.xml
- backbone/src/main/res/values-de-rDE/strings.xml
- backbone/src/main/res/values-en-rAU/strings.xml
- backbone/src/main/res/values-en-rGB/strings.xml
- backbone/src/main/res/values-en-rNZ/strings.xml
- backbone/src/main/res/values-es-rES/strings.xml
- backbone/src/main/res/values-es-rMX/strings.xml
- backbone/src/main/res/values-es-rUS/strings.xml
- backbone/src/main/res/values-fr-rBE/strings.xml
- backbone/src/main/res/values-fr-rCA/strings.xml
- backbone/src/main/res/values-fr-rCH/strings.xml
- backbone/src/main/res/values-fr-rFR/strings.xml
- backbone/src/main/res/values-hu-rHU/strings.xml
- backbone/src/main/res/values-it-rIT/strings.xml
- backbone/src/main/res/values-ja-rJP/strings.xml
- backbone/src/main/res/values-nl-rBE/strings.xml
- backbone/src/main/res/values-nl-rNL/strings.xml
- backbone/src/main/res/values-pl-rPL/strings.xml
- backbone/src/main/res/values-ru-rRU/strings.xml
- backbone/src/main/res/values-ru-rUA/strings.xml
- backbone/src/main/res/values-sv-rSE/strings.xml
- backbone/src/main/res/values-tr-rTR/strings.xml
- backbone/src/main/res/values-uk-rUA/strings.xml
- backbone/src/main/res/values-zh-rCN/strings.xml
- backbone/src/main/res/values-zh-rTW/strings.xml
- backbone/src/main/res/values/non-translatable.xml
- backbone/src/main/res/values/strings.xml
https://jira.devops.medable.com/browse/PAT-1425
task: Extracting all strings "translatable=false" into a file named: non-translatable.xml file to be located in "values"
Addtional changes:
- In ru-RU strings changed `rsb_chart_pie_value` from `%1$s%` to `%1$s&#65285;`
- Changed `rsb_please_wait` eclipses to `&#8230`; in hu and ru
- Changed `Ok` or `ok`to `OK` in all en languages as been notified as warning in the Android Studio
> task/Extract NON-TRANSLATABLE string into a separate file

- backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
- backbone/src/main/java/org/researchstack/backbone/ui/permissions/PermissionMediator.java
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- Fixes PAT-1403 Making sure that when we grant permission for Location Step, the layout gets refreshed.
- How: I added a new method in `PermissionMediator` to take `PermissionListener` that is notified when the permission result is reached.
- Why: Because the Location Step isn't a layout. and therefore is going to be visited when we call the normal `PermissionMediator.requestPermission()` and expect the result in `TaskActivity.onRequestPermissionsResult()`
- Please follow instructions for PAT-1403 (link below)
- PAT: task/PAT-1294-review-step
- Axon: bug/PAT-1402_PAT-1403_fix_overlap_step_views
- RS: bug/PAT-1402_PAT-1403_fix_overlap_step_views
- https://jira.devops.medable.com/browse/PAT-1403
Closes PAT-1402, PAT-1403
> PAT-1403: Fixed granting permission for location step to refresh the layout

- backbone/src/test/java/org/researchstack/backbone/task/OrderedTaskTest.java
- backbone/src/test/java/org/researchstack/backbone/task/TaskTest.java
A couple of unit tests were failing due to being outdated. The implementations have changed and the tests were missing info.
> Fix outdated unit test(s).

- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
- Fix PAT-1433 -> Hidden steps are visible when we go back from next step.
- How: resolved this by keeping track of the last visible step (ReviewStep in our case), and finding the first visible step before that one.
- Why: This is to avoid having issues when we have more than one consecutive hidden steps.
- Please follow instructions for 1433 (link below)
- PAT: task/PAT-1294-review-step
- Axon: bug/PAT-1433-hidden_steps_visible_when_back_pressed
- RS: bug/PAT-1433-hidden_steps_visible_when_back_pressed
- https://jira.devops.medable.com/browse/PAT-1433
Closes PAT-1433
> PAT-1433: hidden steps visible when back is pressed

- backbone/src/main/java/org/researchstack/backbone/ui/step/fragments/BaseStepFragment.kt
- backbone/src/main/res/layout/rsb_review_step_header_layout.xml
- backbone/src/main/res/values/styles.xml
* Produce scrollable headers in the ReviewStep list. 
* Respect ReviewStep title/description in said header. 
* In order to avoid using a NestedScrollView (Which disrupts the RecyclerView internal functioning), I've added a new step type: `ReviewStepInternalHeader`, that maps to `StepType.ReviewStepHeader`.
* The Dummy type is handled by the Adapter, and not Axon or Backbone themselves, that is why this object is not on Axon. It's an artifact that pertains the ReviewStep adapter alone.
* The RecyclerView layout has been stripped of the hardcoded title/description.
* The meat of this Pull Request is only visible on Axon. 
1. Check out the same branch (`task/PAT-1434_reviewstep_headers`) in both **Axon** and **ResearchStack**.
2. Reach the end of any task with a ReviewStep and observe the …
> PAT-1434: Make ReviewStep headers dynamic and scrollable.

- backbone/src/main/java/org/researchstack/backbone/result/TaskResult.java
- Making sure that ReviewStep works for Eligibility tasks
- Fixing a crash In ReviewStep when we include "Health Data Permission" step in Eligibility task.
- Fixing a crash when we include "Health Data Permission" step in Eligibility task and we try to edit any previous step (by using edit button in ReviewStep).
- Credentials:
- Environment: int-dev
- Steps:
2. Join Study (without account)
3. Take task `Eligibility ReviewStep`
4. Reach to ReviewStep
- Make sure you can Scroll through all ReviewStep steps
- Make sure that you can edit any of the editable ReviewStep steps.
- PAT: task/PAT-1294-review-step
- Axon: task/PAT-1447_ReviewStep_for_Elegibility_task
- RS: …
> PAT-1447 review step for eligibility task

- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- PAT-1444 Fixed Step titles when we edit steps that are part of ReviewStep.
- By un-assigning the actionBar from navigation component, and clearing the actionBar title in case of editing, and showing it back when we go to ReviewStep
- Credentials:
- Environment: int-dev
- Steps:
2. Join Study
3. Take task `ReviewStep Boolean`
4. Reach to ReviewStep
5. Edit any of the steps
- Expected: the action bar must be empty, showing no title
- PAT: task/PAT-1294-review-step
- Axon: task/PAT-1294-review-step
- RS: bug/PAT-1444_step_titles_incorrect_when_editing
- https://jira.devops.medable.com/browse/PAT-1444
Closes PAT-1444
> PAT-1444: Fixed Step titles when editing steps

- backbone/src/main/java/org/researchstack/backbone/result/TaskResult.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/fragments/BaseStepFragment.kt
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
Fix when user go back in the middle of branch XX and change his/her answers to branch YY, `taskResult` will hold the answers of the discarded branch 
Fix when user went back back back back back from branch Y .... all the way back to the branch decision and changed the response to now go to branch X. He then hit next/skip etc to complete branch X and finally the review step had all the branch Y+branch X steps...
> Fix Error when going back will save steps from different branchs

- backbone/src/main/java/org/researchstack/backbone/result/Result.java
- backbone/src/main/java/org/researchstack/backbone/result/StepResult.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
- Fixed PAT-1462 - [ReviewStep] Cancel editing should not show dialog if there are no changes.
- How:
- By keeping track of the changes and comparing the original object with the changed one.
- Had to add some code to make sure we are cloning `StepResult` in a correct way.
- By setting `TaskResult` to the changed values in case of Form step
- Credentials:
- Environment: Int-dev
- Steps:
1- Open Patient App
2- Use the credentials above
3- Join Study
4- Start task "ReviewStep Boolean"
5- Take all steps until you reach to ReviewStep
6- Edit any of the steps
7- Tap Cancel
**Note:** Please make sure you test this scenario with Form Step as well, as it is treated differently.
- Expected:
Cancel button should take us right back to ReviewStep
- Actual:
A …
> PAT-1462 fixed showing confirmation dialog when cancelling edit for unchanged step

- backbone/build.gradle
PAT-1475
Block screenshots for dev and prod but not for automatedFlask.
Test:
* Checkout https://gitlab.medable.com/axon/android/sdk/merge_requests/575
* Try to take a screenshot inside of a Task
* Verify that it doesn't let you take a screenshot
> PAT-1475 Block screenshots for dev and prod but not automatedFlask

- backbone/src/main/java/org/researchstack/backbone/ui/ViewTaskActivity.java
Fixing hidden step when it's configure as the first step in a task.
How to reproduce this:
- Just follow the steps described here https://jira.devops.medable.com/browse/PAT-1480
> PAT-1420: Hidden Step: is displayed if it's the first step of a task.

- backbone/src/main/res/layout/rsb_web_view_step_layout.xml
- Removing Edit button from WebView in ReviewStep, as it should not be editable
- Credentials:
- Environment: int-dev
- Steps:
2. Join Study
3. Take task `ReviewStep WebView`
4. Reach to ReviewStep
- Axon: task/PAT-1354_Handle_response_types_in_WebView_ReviewStep
- RS: task/PAT-1354_Handle_response_types_in_WebView_ReviewStep
- https://jira.devops.medable.com/browse/PAT-1354
Closes PAT-1354
> PAT-1354: Removing Edit button from WebView in ReviewStep

- backbone/src/main/java/org/researchstack/backbone/result/StepResult.java
* Ensure equals/hashCode behaves as expected when comparing `StepResult` objects.
* Axon MR will include this change and use it in a Unit Test. Nothing to do here.
> PAT-1498: Fix equals for StepResult to include AnswerFormat.

- backbone/src/main/res/layout/rsb_image_choice_step_layout.xml
- backbone/src/main/res/values/styles.xml
- Adding ImageChoice text under the selected image in the ReviewStep
Study: QA - Regression
User: angela+q33@medable.com/qpal1010
**Location**
This bug happens in the Image choice task
When user is on the Review step, it is not displaying the Image text for selected images.
**Steps:**
1) Launch PAT APP
2) Login study of precond
3) Select Task: T11 - Image Choice
4) Complete all the steps and reach Review step
**Actual result**
Notice that it is not displaying the Image text for selected images.
**Expected result**
It should display tthe Image text for selected images
(See zeplin design)
https://app.zeplin.io/project/5d8e16c2db3c0d61aac43a5f/screen/5da0bfe5ae6da730a33d983a
- Axon: …
> PAT-1500: Adding image text under ImageChoice image in ReviewStep

- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
- Fixed PAT-1508 app is crashing when editing steps with branching logic
- By checking if the next step is `RSCompletionStep`, it should follow the same approach as `RSReviewStep`
Study: QA - Regression
User: angela+q33@medable.com/qpal1010
**Task:** https://app.qa.medable.com/hybridstudy/axon/study/5c76bc486ce0200100f8e68f/task/5dadb526f8332101005cf79e
**Location**
This bug happens in the any task with branching logic
When user edits a step using a branching logic, the app is crashing.
**Preconditions:**
Have a step with a branch configured
**Steps:**
1) Launch PAT APP
2) Login study QA-Regression
3) Select Task: Branching task PAT-1508- do not modify
4) Select Yes and click Next --> Review step
5) Select edit …
> PAT-1508: Resolved crash when editing steps with branching logic

- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
- Fixed PAT-1484: Having invalid Date/Time in an optional step doesn't prevent the user to go to next step.
Environment: Int-Dev
Org: abdallahandela
Study: Banadol
**Steps:**
1. Join Study
2. Select task "ReviewStep DateTime"
3. Reach step 'Optional with Min and Max'
4. Tap on the field and select 2019-12-31 07:00 AM
5. Tap 'OK'
6. Verify error message is displayed
7. Tap on 'Next'
**Actual result**
Next button is functional and takes you to the next step which shows the step result as "Skipped"
**Expected result**
Next button shouldn't take the user to next screen and show a toast instead
**Note:** Please make sure this works when you edit this Date/Time step
- Axon: bug/PAT-1484_DateTime_invalid_time_is_accepted
- RS: …
> PAT-1484: Date/Time User is able to enter an invalid time and tap next

- backbone/src/main/java/org/researchstack/backbone/ui/step/fragments/BaseStepFragment.kt
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentDocumentStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentSignatureStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentVisualStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/InstructionStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/StepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- Fixed PAT-1468: Form: when updating location permissions, the form is cleaned up
Study: QA - Regression
User: angela+q33@medable.com
When user updates location permissions on a form, the completed fields are cleaned up.
**Video link**
https://drive.google.com/open?id=1exwLskc0bueTnm3oRUnTXxmSDITmmfVV
**Steps:**
1) Launch PAT APP
2) Login study of precond
3) Select T08- Form
4) Complete all the fields
5) In the location step, allow permissions
**Actual result**
Notice that completed fields are cleaned up in the form
**Expected result**
Completed fields should remain with selected information.
- Axon: bug/PAT-1468_Update_permission_clears_form
- RS: bug/PAT-1468_Update_permission_clears_form
- …
> PAT-1468: Form: when updating location permissions, the form is cleaned up

- backbone/src/main/java/org/researchstack/backbone/ui/step/fragments/BaseStepFragment.kt
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
- backbone/src/test/java/org/researchstack/backbone/ui/task/TaskViewModelTest.kt
- Fixed PAT-1486: When going back to step, previous answers not saved
Study: QA Regression
When a user is on the Numeric review step and then goes back to previous steps, the values previously entered are not saved.
**Steps**
1) Launch the Pat App
2) Login to QA regression
3) Select T14- Numeric task
4) Complete all the steps and reach Review step
5) Select back until S01
6) Click Next
**Actual Result:**
Previously entered values are not saved, after optional step.
**Expected Result:**
Previously entered values should be saved.
**Note:** Please make sure you test this with a branching task as well.
- RS: bug/PAT-1486_Fix_step_results_when_going_back_and_forward
- Cortex: …
> PAT-1486: When going back to step, previous answers not saved

- backbone/build.gradle
Set USE_SECURE_FLAG to false in dev flavor and remove automatedFlask flavor from RS gradle file 
Branches:
1. PAT: task/PAT-1612_update_class_to_USE_SECURE_FLAG
2. Axon: task/PAT-1612_update_class_to_USE_SECURE_FLAG
3. Cortex: development
4. RS: task/PAT-1612_update_class_to_USE_SECURE_FLAG
How to test :
Go to gradle file in backbone and check for the USE_SECURE_FLAG in dev flavor is set to false and automatedFlask flavor is removed
> PAT-1612 : Update classes related with USE_SECURE_FLAG from Pat gradle and remove automatedFlask flavor from all modules

- backbone/src/main/res/drawable/rsb_form_step_reviewstep_rect.xml
- backbone/src/main/res/layout/rsb_form_section_step_layout.xml
- backbone/src/main/res/layout/rsb_form_step_layout.xml
- backbone/src/main/res/layout/rsb_review_step_edit_button_layout.xml
- backbone/src/main/res/values/dimens.xml
- backbone/src/main/res/values/styles.xml
* Adjust the ReviewStep UX to match the new Zeplin comps and fix some inconsistencies.
* The bulk of this work ended up being the new change to display the Titles of "Sub Steps" (where SubStep is just a regular step but inside a FormStep). Previously when a step was in a FormStep, the title was not rendered by the ReviewStep app. Now it has to be rendered. 
* The FormSection view holder (a section *only* used inside FormSteps), also changed appearances and now has a divider line. 
* The TypeValueResolver abstraction was removed, and all DP values were added to the Resources/Dimensions and extracted from there. All unit tests were updated to reflect this. 
* The spacing between multi-line answers was adjusted (via lineMultiplier) and the thickness of the FormStep container border has been …
> PAT-1593: Various ReviewStep UX fixes

- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
- Fixed PAT-1700: Fixed editing a step that is before `RSGoogleFitPermissionsStep`
The `RSGoogleFitPermissionsStep` has no result, so when we were checking if there are any branches for a task, we were checking if the next step result is null, and in case of GFit, it is always null. so the code assumed that this task has branches, even when it didn't.
-  Environment: QA
-  Org: Hybridstudy
-  Study: QA-Regression
-  User: angela+q33@medable.com / qpal1010
-  Task: https://app.qa.medable.com/hybridstudy/axon/study/5c76bc486ce0200100f8e68f/task/5c76bc4b6ce0200100f8e7e9
**Steps**
1.  Launch Flask
2.  Login with valid credentials
3.  Start task T00 - All Step Types Survey- do not modify PAT-1700
4.  Reach the review step
5.  Select Edit next to Form step
6.  Edit any …
> PAT-1700: Fixed editing any step type before GoogleFitPermission step

- backbone/src/main/java/org/researchstack/backbone/ui/step/body/TextQuestionBody.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentDocumentStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentSignatureStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/InstructionStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- backbone/src/main/java/org/researchstack/backbone/ui/views/SignatureView.java
- backbone/src/main/java/org/researchstack/backbone/ui/views/SubmitBar.java
The goal of this MR is to fix the button and some view labels string are not displayed in the preferred locale
PAT: rc/flask-4.10.0
Axon: bug/PAT-1727_update_string_in_buttons
RS: bug/PAT-1727_update_string_in_buttons
Cortex: rc/flask-4.10.0
env : qa
org : hybridstudy
study : Multi-language Study
- Launch patient app with a non supported locale (Arabic :P)
- Set the study of the preconditions
- Set Ukrainian....etc as preferred locale
- Reach the welcome screen
- Press join study
- Select a consent task
- Reach the first and last name screen
- Observe all the strings, The buttons and all of the fields are being displayed in preferred locale
> PAT-1727 : Update strings according to user selected locale

- backbone/src/main/java/org/researchstack/backbone/ui/task/ReviewStepFullScreenImageActivity.kt
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- Fixed PATAND-19: Added secure flag to TaskActivity to prevent taking screenshot for the android task manager
-  Environment: QA
-  Org: Hybridstudy
-  Study: QA-Regression
-  User: angela+q33@medable.com / qpal1010
**Location**
The issue occurs when the user is currently inside any task of the app.
A blank screen is not shown when the user is within a task and moves the app into the background, like using the Android's Task Manager.
**Steps:**
1.  Launch PAT using the credentials above
2.  Select any valid task
3.  Put the app in the background and open Android's task manager.
**Actual Result:** The preview of the app is displayed, including the current step data.
**Expected Result:** The app's preview should show a blank image, without any …
> PATAND-19: Added secure flag to TaskActivity

- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- backbone/src/main/java/org/researchstack/backbone/utils/LocaleUtils.java
**Description 👍**
The goal of this MR is to fix the button and some view labels string, date picker dialogs buttons are not displayed in the preferred locale 
**Branches**
PAT: development 
Axon: bug/PATAND-52_update_locale 
RS: bug/PATAND-52_update_locale 
Cortex: development
**Credentials :**
env : qa
org : hybridstudy
study : Multi-language Study
How to test :
**SCENARIO 1**
Launch pat from scratch 
Set Japanese ....etc as preferred locale
Press join study
Do all the tasks
Observe all the strings, The buttons and all of the fields are being displayed in preferred locale
**SCENARIO 2**
Launch pat  ( with your account )
Put your username/password
Set Italiano ....etc as preferred locale
Do all the tasks
Observe all the strings, The buttons and all of the fields are being displayed in …
> PATAND-52 : Make sure Task loads preferred locale String

- backbone/src/main/java/org/researchstack/backbone/step/ConsentVisualStep.java
- backbone/src/main/java/org/researchstack/backbone/task/OrderedTask.java
- backbone/src/main/java/org/researchstack/backbone/task/Task.java
- backbone/src/main/java/org/researchstack/backbone/ui/ConsentTaskActivity.kt
- backbone/src/main/java/org/researchstack/backbone/ui/step/body/BodyAnswer.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/body/DecimalQuestionBody.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/body/IntegerQuestionBody.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/body/TextQuestionBody.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentDocumentStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentSignatureStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentVisualStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/InstructionStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskActivity.kt
- backbone/src/main/java/org/researchstack/backbone/ui/views/SignatureView.java
- backbone/src/main/java/org/researchstack/backbone/ui/views/SubmitBar.java
- backbone/src/main/java/org/researchstack/backbone/utils/LocalizationUtils.java
- Implement PATAND-42: Handle and report time zone changes
- Renamed `LocaleUtils` to `LocalizationUtils`
- Added TimeZone setter and getter in LocalizationUtils for storing the TZ in SharedPreferences
For now in order to test this:
1. Filter the logcat with `LocalizationDelegate`
2. Debug the `LocalizationDelegateImpl.reportTimeZoneAndLocale()` method to make sure we're sending the correct TZ and locale
- Study: Multi-language
1. Open the app using the credentials above
2. Put it in the background
3. Change the device's time zone
4. Bring back the app to the foreground
**Expected:** This should update the TimeZone in SharedPreferences and send it (along with the current locale) to the backend.
1. Open the app using the credentials above
2. Join Study …
> PATAND-42: Handle And Report TZ and Locale Changes

- backbone/src/main/java/org/researchstack/backbone/ui/step/fragments/BaseStepFragment.kt
- Fixed PATAND-123: Consent review step view is broken after opening task manager and returning
- The problem is the view is rendered at onResume() method, so when you go to the background and back to the app again the view is re-rendered again that's why you see the view is broken
- So my solution is mainly remove rendering the view from onResume() to onViewCreated()
- Study: Multi-language study
If the user is in the Consent Review section and he opens the task manager and go back to the Consent review, the view of the task is broken displaying a separate block of options as it was a normal step with the options to Skip or Next (which are actually not interactive).
**Steps:**
.  Fresh launch the Android app
. …
> PATAND-123: Consent review step view is broken after opening task manager and returning

- backbone/src/main/res/values-ja-rJP/strings.xml
Update Counter Formats in Header on Japanese Screens please check the screenshot in this [ticket](https://jira.devops.medable.com/browse/PATAND-196)
PAT: development
Axon: development
Cortex: development
RS: bug/PATAND-196
Org: hybridstudy
Study: ML
1- lunch PAT
2- login/join study
3- go to profile and choose the Japanese language
4- start any task
Expected result:  the header count should be 1 / 2 NOT 2/1
> Patand 196 : Update Counter Formats in Header on Japanese Screens

- backbone/src/main/java/org/researchstack/backbone/ui/ConsentTaskActivity.kt
- backbone/src/test/java/org/researchstack/backbone/ui/ConsentTaskTest.kt
This MR is for adding the time, hour and TZ on the consent pdf.
- RS: task/PATAND-201_add_time_to_pdf
- Environment: Int-Dev
- Study: Multi-language study
- User: a public user
* Start as a public user
* Do the consent task. 
* After the upload, display the PDF
* Expected result: The date display on the bottom right also display the hour, minute and timezone
Close PATAND-201
> PATAND-201: Add time, hour and TZ on the consent pdf

- backbone/src/main/java/org/researchstack/backbone/ui/ConsentTaskActivity.kt
This MR fix a crash occurring when we disagree to a ConsentTask and when we press back on the ConsentTask.
- RS: task/PATAND-189_fixing_crash_when_disagree
- Environment: Int-Dev
- Study: Multi-language study
* Use a public user then on the consent task disagree on the consent review. 
* **Expected result** : The consent will start again after the upload of the task and no crash will happen
- Study: fede study emtpy
- User: fforciniti+03test@medable.com/qpal1010
* Login then start the only task (docu). Just press back. 
* **Expected result** : No crash and the task will not start automatically again
Close PATAND-189, PATAND-225
> PATAND-189, PATAND-225: Fixing the crash when we disagree the ConsentTask

- backbone/src/main/java/org/researchstack/backbone/ui/task/TaskViewModel.kt
Fixing task responses not being uploaded after a session timeout.
although the ticket says that this happens with consent tasks, this should happen with any task type once you are logged in and a session timeout is fired
How to test this:
1- on a fresh install, select QA -> hybrid study -> Qa regression
2- Complete Eligibility, consent, and auth tasks
3- Open "Consent A" task (don't complete the task)
4- Wait enough time so that the session times out
5- Complete the consent task
6- Uploading response dialog will be shown, and the you should be redirected to the login screen
7- Login and wait until all the data is loaded
8- Go to the web portal, and check that the task response is there
9- Go to the profile screen, select consent option, and make sure that you see all the consents you …
> PATAND-233: Consent Task: The consent task is not uploaded after a timeout.

- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/InstructionStepLayout.java
- backbone/src/main/res/layout/rsb_step_layout_instruction.xml
- backbone/src/main/res/layout/rsb_view_submitbar.xml
Implement the change for the completion step
- RS: task/PATAND-248_instruction_step
- Study: QA-Regression
- User: matias.battaglia+4@medable.com/qpal1010
- Task: instruction test
* Login if it's not the case
* Start the right task
Expected: 
* The new UI will fit the new ui (same margin that the other, etc.) There is none zeplin for this one
Close PATAND-248
> PATAND-248: Update instruction layout

- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentDocumentStepLayout.java
* Fixed PATAND-329: Double click on Agree button bypass step from the Consent
* Environment: QA
* Org: hybridstudy
* Study: QA-regression
* New user
**Steps:**
1. Open the app as a new user
2. Start Consent task
3. Complete all steps until the review step
4. Double click very fast at Agree button in submit bar
**Expected:**
* Only one confirmation dialog will appear and by pressing on agree on it move to the next step
* PAT: bug/PATAND-329
* Axon: bug/PATAND-329
* RS: bug/PATAND-329
* Cortex: development
* https://jira.devops.medable.com/browse/PATAND-329
Closes PATAND-329
> PATAND-329: Double click on Agree button bypass step from the Consent

- backbone/src/main/res/layout/rsb_form_step_layout.xml
- Fixed PATAND-348: Showing full title for Form steps in ReviewStep
When we first created ReviewStep, we added the line `app:layout_constrainedHeight="true"` to most of the view holder's layout views, basically it was added to make sure the edit button does not overlap with the user answer, but for the form step this should not be the case since there is already another `Barrier` that prevents this from happening, so I'm just removing that line here.
- Environment: Int-Dev
2. Join Study
3. Take task `Html Form` (last one in the list)
4. Skip the form step
The full step title should appear:
- RS: bug/PATAND-348
- PAT, Axon, Cortex -> development
- https://jira.devops.medable.com/browse/PATAND-348
Closes …
> PATAND-348: Fix Showing full title for Form steps in ReviewStep

- backbone/build.gradle
- backbone/src/main/res/layout/rsb_item_edit_text_compact.xml
This MR is to update the library version of com.google.android.material:material to 1.2.0-beta01 to avoid this because of [this](https://gitlab.medable.com/axon/android/sdk/pipelines/36356) CI error
**Branches**
- PAT: bug/PATAND-328
- Axon: bug/PATAND-328
- RS: bug/PATAND-328
**Credentials**
- Study: ML or QA
**Scenario**
- Open Pat
- Start consent
- Reach consent Form step, it should match this
https://zpl.io/VDE3mpq
https://zpl.io/Vkq9lpg
> PATAND-328: Consent: design of Name insert screen is not correct 

- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentDocumentStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentSignatureStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/ConsentVisualStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/FormStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/InstructionStepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/StepLayout.java
- backbone/src/main/java/org/researchstack/backbone/ui/step/layout/SurveyStepLayout.java
Fix the skip button when on an form step
- Axon: bug/PATAND-372_issue_when_editing_form_step
- RS: bug/PATAND-372_issue_when_editing_form_step
- Study: QA - Regression
- matias.battaglia+4@medable.com/qpal1010
- Task : T08 - Form
* Log in
* Start the task and do all the step
* On the review step edit a step
* Try to skip it then cancel the skip.
* Save the value
The previous value is keep and there is no error when trying to save it
Close PATAND-372
> Patand-372 : Fixing the skip button on edit step (for the form step)
